name: acceptance-tests-secondary
on:
  pull_request:
    paths:
      - 'java/**'
      - 'web/html/src/**'
      - 'testsuite/**'
      - '.github/workflows/acceptance_tests_secondary.yml'
      - '.github/workflows/acceptance_tests_common.yml'
      - '!java/*.changes*'
  schedule:
    - cron: '0 6 * * *'
jobs:
  pre-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :wave: Hello! Thanks for contributing to our project :smile:
  test-uyuni:
    uses: ./.github/workflows/acceptance_tests_common.yml
    with:
      secondary_tests: "17_run_secondary_tests.sh" 
      server_id: "secondary"

