name: acceptance-tests-feedback
on:
  pull_request_target:
    paths:
      - 'java/**'
      - 'web/html/src/**'
      - 'testsuite/**'
      - '.github/workflows/acceptance_tests_secondary.yml'
      - '.github/workflows/acceptance_tests_common.yml'
      - '!java/*.changes*'
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :wave: Hello! Thanks for contributing to our project :smile:
            :coffee: Acceptance tests will take same time (aprox. 1h)
            :eyes: Once tests finish, you can check the cucumber report.
            See the [troubleshooting guide](https://github.com/uyuni-project/uyuni/wiki/Running-Acceptance-Tests-at-PR#troubleshooting) if you need any help.
            :warning: You should not merge if acceptance tests fail to pass
            Happy hacking

