name: acceptance-tests-feedback
on:
  pull_request_target:
    paths:
      - 'java/**'
      - 'web/html/src/**'
      - 'testsuite/**'
      - '.github/workflows/acceptance_tests_secondary.yml'
      - '.github/workflows/acceptance_tests_secondary_parallel.yml'
      - '.github/workflows/acceptance_tests_feedback.yml'
      - '.github/workflows/acceptance_tests_common.yml'
      - '!java/*.changes*'
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions-cool/maintain-one-comment@v3
        with:
          body: |
            :wave: Hello! Thanks for contributing to our project.
            Acceptance tests will take some time (aprox. 1h), please be patient :coffee:
            You can see the progress at the end of this page and at https://github.com/uyuni-project/uyuni/pull/${{ github.event.pull_request.number  }}/checks
            Once tests finish, if they fail, you can check :eyes: the cucumber report. See the link at the output of the action.
            You can also check the artifacts section, which contains the logs at https://github.com/uyuni-project/uyuni/pull/${{ github.event.pull_request.number }}/checks.
            See the [troubleshooting guide](https://github.com/uyuni-project/uyuni/wiki/Running-Acceptance-Tests-at-PR#troubleshooting) if you need any help.

            Happy hacking!
            
          body-include: ":warning: You should not merge if acceptance tests fail to pass. :warning:" 

