name: changelog_test

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  changelog_test:

    runs-on: [self-hosted, linux]
    container: registry.opensuse.org/systemsmanagement/uyuni/master/docker/containers/uyuni-master-base:latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run a changelog checker
      run: |
        files_modified=`git diff --name-only "origin/$GITHUB_BASE_REF..HEAD" | xargs`
        ruby .github/scripts/changelog.rb "$files_modified"
        
  changelog_approved:
    needs: changelog_test
    runs-on: [self-hosted, linux]
    
    steps:
    - name: Changelogs approved
      run : echo "Changelogs approved"
