name: Java checkstyle

on:
  pull_request:
    paths:
      - 'java/**.java'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/systemsmanagement/uyuni/master/docker/containers/uyuni-master-pgsql:latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: java/lib
        key: ${{ runner.os }}-jars-${{ hashFiles('java/buildconf/ivy/*.*') }}

    - name: Resolve dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        echo '${{ secrets.OSCRC_CONTENTS }}' > ~/.oscrc
        ant -f java/manager-build.xml ivy

    - name: Run checkstyle
      run: ant -f java/manager-build.xml checkstyle
