name: Labeler
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: paulfantom/periodic-labeler@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        LABEL_MAPPINGS_FILE: .github/labeler.yml
