name: RuboCop

on:
  pull_request:
    branches:
      - Manager-4.1
      - Manager-4.1-MU-4.1.[0-9]
      - Manager-4.1-MU-4.1.[0-9][0-9]  
    paths:
      - 'testsuite/features/**.rb'

jobs:
  rubocop:

    runs-on: [self-hosted, linux]
    container: registry.opensuse.org/systemsmanagement/uyuni/master/docker/containers/uyuni-master-base:latest

    steps:
    - uses: actions/checkout@v2
      with:
        ruby-version: '2.5'

    - name: Install rubocop
      run: |
        gem install rubocop
        ln -s /usr/bin/rubocop.ruby* /usr/bin/rubocop

    - name: Run RuboCop
      run: |
        cd testsuite
        rubocop features/*
