name: test-all-in-one-p2
on: pull_request
jobs:
  test-uyuni:
    uses: ./.github/workflows/test_all_in_one_common.yml
    with:
      secondary_tests: "18_run_secondary_parallelizable_tests_subset.sh 2"
