name: ignore-me
on:
- pull_request_target
jobs:
  test-uyuni:
    runs-on: ubuntu-latest
    steps:
      - name: hello_world
        run: echo "This is a test. Please ignore. 4!"
      - name: test_from_container
        run: docker run -a stdout -a stderr --network uyuni_default ghcr.io/uyuni-project/uyuni/controller-dev:master bash -c "echo helloworld"
      - name: last-step
        run: echo "bye bye!"


